[server]
maxMessageSize = 350

[browser]
gatherUsageStats = false

[global]
disableWidgetStateDuplicationWarning = true

[logger]
level = "info"

[client]
showErrorDetails = false
toolbarMode = "viewer"
